### ISSUE TITLE
Support static properties

### ISSUE THREAD

**Issue by rgbkrk** [pbomb/flow-immutable-models#20]
When a type has a static string like `cell_type` below here:

```js
export type MarkdownCellType = {
  cell_type: 'markdown',
  source: string,
}

export type CodeCellType = {
  cell_type: 'code',
  source: string,
  outputs: Immutable.List<string>,
}

export type Cell = MarkdownCellType | CodeCellType;
```

It would be great if the generated class set `cell_type` as a static property on the generated class.

/cc @peggyrayzis

**Comment by pbomb** [comment]
This has been fixed in v0.10.0
